kind: pipeline
name: default

steps:
- name: build
  image: maven:3-alpine
  commands:
    - mvn -DskipTests clean package

- name: publish
  image: plugins/docker
  settings:
    mirror: https://docker.mirrors.ustc.edu.cn
    registry: registry.cn-hangzhou.aliyuncs.com # 仓库
    repo: registry.cn-hangzhou.aliyuncs.com/lm93129/drone # docker仓库地址
    tags: latest
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
    purge: true
  when:
    branch:
      - master
      
- name: publish_autotag
  image: plugins/docker
  settings:
    mirror: https://docker.mirrors.ustc.edu.cn
    registry: registry.cn-hangzhou.aliyuncs.com # 仓库
    repo: registry.cn-hangzhou.aliyuncs.com/lm93129/drone # docker仓库地址
    auto_tag: true
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
  when:
    event:
    - tag
